package com.tss.aml.entity.enums;

public enum RuleType {
	THRESHOLD, GEOGRAPHIC, FREQUENCY, KEYWORD, PATTERN,  VELOCITY,FUNNEL_ACCOUNT, 
	CASH_WIRE_VELOCITY, GRAPH_BEHAVIOR, GRAPH_PATTERN,KYC,NETWORK,BEHAVIOR
}